### ISSUE TITLE
控制台信息

### ISSUE THREAD

**Issue by Clound-11** [react-ld/react-wx-images-viewer#1]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

可以消除吗。

**Comment by lidianhao123** [comment]
@Clound-11 感谢对本组件的支持！
近期会抽空研究一下这个问题。目前的考虑是移除触摸事件中 preventDefault 函数的调用。

**Comment by lidianhao123** [comment]
@Clound-11  发现一种通过 css 设置解决控制台警告的方式：
```css
.wx-image-viewer .viewer-image-container {
  touch-action: none;
}
```
给绑定 touchstart 的 Dom 元素加上 touch-action: none; 即：当触控事件发生在元素上时，不进行任何操作。

具体参考 [touch-action]( https://developer.mozilla.org/zh-CN/docs/Web/CSS/touch-action)
